name: Java CI with Gradle

on:
  push:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Install dos2unix
        run: sudo apt-get install -y dos2unix

      - name: Convert line endings to LF
        run: dos2unix gradlew

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t toktalk-cicd .
          docker tag toktalk-cicd kokyungbum/toktalk-cicd:${GITHUB_SHA::7}
          docker push kokyungbum/toktalk-cicd:${GITHUB_SHA::7}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to Server
        run: |
          aws ssm send-command \
            --instance-ids i-05ee53499ed8f891d \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[ 
              'if sudo docker ps -a --format \\'{{.Names}}\\' | grep -q \\'^server$\\'; then',
              '  sudo docker stop server',
              '  sudo docker rm server',
              'fi',
              'sudo docker pull kokyungbum/toktalk-cicd:${GITHUB_SHA::7}',
              'sudo docker tag kokyungbum/toktalk-cicd:${GITHUB_SHA::7} toktalk-cicd',
              'sudo docker run -d --name server -p 8080:8080 toktalk-cicd'
            ]" \
            --output text
